FROM python:3.11

WORKDIR ./

RUN pip install uv

#pour copier tout le code  
COPY . .

RUN uv sync --no-dev --locked

RUN uv pip install gunicorn

#var d'env dans les fichiers de config nomad


EXPOSE 8080


CMD ["uv", "run", "--no-dev", "gunicorn", "--workers", "4", "--bind", "0.0.0.0:8080", "image_api.web:app"]